//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestaurantService
{
    using System;
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System.Collections;
    using System.Xml.Schema;
    using System.ComponentModel;
    using System.Runtime.Serialization;
    using System.Collections.Generic;
    using CServiceStack.ProtoBuf;
    using CServiceStack.ServiceHost;
    using CServiceStack.Common.Types;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soa.ctrip.com/framework/soa/sample/message/v1")]
    [System.Xml.Serialization.XmlRootAttribute("GetRestaurantsRequest", Namespace="http://soa.ctrip.com/framework/soa/sample/message/v1", IsNullable=false)]
    [DataContract(Name="GetRestaurantsRequest", Namespace="http://soa.ctrip.com/framework/soa/sample/message/v1")]
    [ProtoContract()]
    public partial class GetRestaurantsRequestType
    {
        
        private string zipField;
        
        [DataMember()]
        [ProtoMember(1)]
        public string Zip
        {
            get
            {
                return this.zipField;
            }
            set
            {
                this.zipField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soa.ctrip.com/framework/soa/sample/message/v1")]
    [System.Xml.Serialization.XmlRootAttribute("GetRestaurantsResponse", Namespace="http://soa.ctrip.com/framework/soa/sample/message/v1", IsNullable=false)]
    [DataContract(Name="GetRestaurantsResponse", Namespace="http://soa.ctrip.com/framework/soa/sample/message/v1")]
    [ProtoContract()]
    public partial class GetRestaurantsResponseType : IHasResponseStatus
    {
        
        private ResponseStatusType responseStatusField;
        
        private List<RestaurantInfo> restaurantsField;
        
        [DataMember()]
        [ProtoMember(1)]
        public ResponseStatusType ResponseStatus
        {
            get
            {
                return this.responseStatusField;
            }
            set
            {
                this.responseStatusField = value;
            }
        }
        
        [System.Xml.Serialization.XmlArrayItemAttribute("Restaurant", Namespace="http://soa.ctrip.com/framework/soa/sample/data/v1", IsNullable=false)]
        [DataMember()]
        [ProtoMember(2)]
        public List<RestaurantInfo> Restaurants
        {
            get
            {
                if ((this.restaurantsField == null))
                {
                    this.restaurantsField = new List<RestaurantInfo>();
                }
                return this.restaurantsField;
            }
            set
            {
                this.restaurantsField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soa.ctrip.com/framework/soa/sample/data/v1")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://soa.ctrip.com/framework/soa/sample/data/v1", IsNullable=true)]
    [DataContract(Namespace="http://soa.ctrip.com/framework/soa/sample/data/v1")]
    [ProtoContract()]
    public partial class RestaurantInfo
    {
        
        private int restaurantIDField;
        
        private string nameField;
        
        private string addressField;
        
        private string cityField;
        
        private string stateField;
        
        private string zipField;
        
        private System.DateTime openFromField;
        
        private System.DateTime openToField;
        
        [DataMember()]
        [ProtoMember(1)]
        public int RestaurantID
        {
            get
            {
                return this.restaurantIDField;
            }
            set
            {
                this.restaurantIDField = value;
            }
        }
        
        [DataMember()]
        [ProtoMember(2)]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        [DataMember()]
        [ProtoMember(3)]
        public string Address
        {
            get
            {
                return this.addressField;
            }
            set
            {
                this.addressField = value;
            }
        }
        
        [DataMember()]
        [ProtoMember(4)]
        public string City
        {
            get
            {
                return this.cityField;
            }
            set
            {
                this.cityField = value;
            }
        }
        
        [DataMember()]
        [ProtoMember(5)]
        public string State
        {
            get
            {
                return this.stateField;
            }
            set
            {
                this.stateField = value;
            }
        }
        
        [DataMember()]
        [ProtoMember(6)]
        public string Zip
        {
            get
            {
                return this.zipField;
            }
            set
            {
                this.zipField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(DataType="time")]
        [DataMember()]
        [ProtoMember(7)]
        public System.DateTime OpenFrom
        {
            get
            {
                return this.openFromField;
            }
            set
            {
                this.openFromField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(DataType="time")]
        [DataMember()]
        [ProtoMember(8)]
        public System.DateTime OpenTo
        {
            get
            {
                return this.openToField;
            }
            set
            {
                this.openToField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soa.ctrip.com/framework/soa/sample/message/v1")]
    [System.Xml.Serialization.XmlRootAttribute("AddRestaurantRequest", Namespace="http://soa.ctrip.com/framework/soa/sample/message/v1", IsNullable=false)]
    [DataContract(Name="AddRestaurantRequest", Namespace="http://soa.ctrip.com/framework/soa/sample/message/v1")]
    [ProtoContract()]
    public partial class AddRestaurantRequestType
    {
        
        private RestaurantInfo restaurantField;
        
        [DataMember()]
        [ProtoMember(1)]
        public RestaurantInfo Restaurant
        {
            get
            {
                return this.restaurantField;
            }
            set
            {
                this.restaurantField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soa.ctrip.com/framework/soa/sample/message/v1")]
    [System.Xml.Serialization.XmlRootAttribute("AddRestaurantResponse", Namespace="http://soa.ctrip.com/framework/soa/sample/message/v1", IsNullable=false)]
    [DataContract(Name="AddRestaurantResponse", Namespace="http://soa.ctrip.com/framework/soa/sample/message/v1")]
    [ProtoContract()]
    public partial class AddRestaurantResponseType : IHasResponseStatus
    {
        
        private ResponseStatusType responseStatusField;
        
        [DataMember()]
        [ProtoMember(1)]
        public ResponseStatusType ResponseStatus
        {
            get
            {
                return this.responseStatusField;
            }
            set
            {
                this.responseStatusField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soa.ctrip.com/framework/soa/sample/message/v1")]
    [System.Xml.Serialization.XmlRootAttribute("RateRestaurantRequest", Namespace="http://soa.ctrip.com/framework/soa/sample/message/v1", IsNullable=false)]
    [DataContract(Name="RateRestaurantRequest", Namespace="http://soa.ctrip.com/framework/soa/sample/message/v1")]
    [ProtoContract()]
    public partial class RateRestaurantRequestType
    {
        
        private int restaurantIDField;
        
        private RatingInfo rateField;
        
        [DataMember()]
        [ProtoMember(1)]
        public int RestaurantID
        {
            get
            {
                return this.restaurantIDField;
            }
            set
            {
                this.restaurantIDField = value;
            }
        }
        
        [DataMember()]
        [ProtoMember(2)]
        public RatingInfo Rate
        {
            get
            {
                return this.rateField;
            }
            set
            {
                this.rateField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soa.ctrip.com/framework/soa/sample/data/v1")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://soa.ctrip.com/framework/soa/sample/data/v1", IsNullable=false)]
    [DataContract(Namespace="http://soa.ctrip.com/framework/soa/sample/data/v1")]
    [ProtoContract()]
    public enum RatingInfo
    {
        
        /// <remarks/>
        [EnumMember()]
        [ProtoEnum()]
        Poor,
        
        /// <remarks/>
        [EnumMember()]
        [ProtoEnum()]
        Good,
        
        /// <remarks/>
        [EnumMember()]
        [ProtoEnum()]
        VeryGood,
        
        /// <remarks/>
        [EnumMember()]
        [ProtoEnum()]
        Excellent,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soa.ctrip.com/framework/soa/sample/message/v1")]
    [System.Xml.Serialization.XmlRootAttribute("RateRestaurantResponse", Namespace="http://soa.ctrip.com/framework/soa/sample/message/v1", IsNullable=false)]
    [DataContract(Name="RateRestaurantResponse", Namespace="http://soa.ctrip.com/framework/soa/sample/message/v1")]
    [ProtoContract()]
    public partial class RateRestaurantResponseType : IHasResponseStatus
    {
        
        private ResponseStatusType responseStatusField;
        
        [DataMember()]
        [ProtoMember(1)]
        public ResponseStatusType ResponseStatus
        {
            get
            {
                return this.responseStatusField;
            }
            set
            {
                this.responseStatusField = value;
            }
        }
    }
    
    /// <summary>
    /// Service interface auto-generated by SOA tool, DO NOT CHANGE!
    /// 
    /// 注意，实现该接口的服务在CServiceStack服务容器中是以new instance per request的形式被初始化的，
    /// 也就是说，容器会为每个请求创建一个新的服务实例，并在请求结束时释放(release)，而不是单个
    /// 服务实例(singleton)服务所有的请求, 所以请务必不要在服务初始化（例如构造函数中）时做较重的初始化
    /// （例如初始化数据库等）动作，否则对性能有很大影响，如果有较重的初始化动作，
    /// 请在服务实现中以静态方式（例如静态构造函数中)一次性完成，或者以IoC注入方式初始化，在服务容器
    /// 启动时事先将依赖初始化并注册在容器中，让容器在构造服务实例时自动解析和注入依赖(也可在服务实现中手动解析依赖)，
    /// 关于静态和依赖注入初始化的样例，请参考CServiceStack提供的样例程序.
    /// 
    /// 
    /// </summary>
    [CServiceInterface("RestaurantService", "http://soa.ctrip.com/framework/soa/sample/v1", "2.0.3.2")]
    public interface IRestaurantService
    {
        
        GetRestaurantsResponseType GetRestaurants(GetRestaurantsRequestType request);
        
        AddRestaurantResponseType AddRestaurant(AddRestaurantRequestType request);
        
        RateRestaurantResponseType RateRestaurant(RateRestaurantRequestType request);
        
        CheckHealthResponseType CheckHealth(CheckHealthRequestType request);
    }
}
