//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestaurantClient
{
    using System;
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System.Collections;
    using System.Xml.Schema;
    using System.ComponentModel;
    using System.Runtime.Serialization;
    using System.Collections.Generic;
    using CServiceStack.ProtoBuf;
    using System.Threading;
    using System.Threading.Tasks;
    using CServiceStack.ServiceHost;
    using CServiceStack.ServiceClient;
    using CServiceStack.Common.Types;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soa.ctrip.com/framework/soa/sample/message/v1")]
    [System.Xml.Serialization.XmlRootAttribute("GetRestaurantsRequest", Namespace="http://soa.ctrip.com/framework/soa/sample/message/v1", IsNullable=false)]
    [DataContract(Name="GetRestaurantsRequest", Namespace="http://soa.ctrip.com/framework/soa/sample/message/v1")]
    [ProtoContract()]
    public partial class GetRestaurantsRequestType
    {
        
        private string zipField;
        
        [DataMember()]
        [ProtoMember(1)]
        public string Zip
        {
            get
            {
                return this.zipField;
            }
            set
            {
                this.zipField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soa.ctrip.com/framework/soa/sample/message/v1")]
    [System.Xml.Serialization.XmlRootAttribute("GetRestaurantsResponse", Namespace="http://soa.ctrip.com/framework/soa/sample/message/v1", IsNullable=false)]
    [DataContract(Name="GetRestaurantsResponse", Namespace="http://soa.ctrip.com/framework/soa/sample/message/v1")]
    [ProtoContract()]
    public partial class GetRestaurantsResponseType : IHasResponseStatus
    {
        
        private ResponseStatusType responseStatusField;
        
        private List<RestaurantInfo> restaurantsField;
        
        [DataMember()]
        [ProtoMember(1)]
        public ResponseStatusType ResponseStatus
        {
            get
            {
                return this.responseStatusField;
            }
            set
            {
                this.responseStatusField = value;
            }
        }
        
        [System.Xml.Serialization.XmlArrayItemAttribute("Restaurant", Namespace="http://soa.ctrip.com/framework/soa/sample/data/v1", IsNullable=false)]
        [DataMember()]
        [ProtoMember(2)]
        public List<RestaurantInfo> Restaurants
        {
            get
            {
                if ((this.restaurantsField == null))
                {
                    this.restaurantsField = new List<RestaurantInfo>();
                }
                return this.restaurantsField;
            }
            set
            {
                this.restaurantsField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soa.ctrip.com/framework/soa/sample/data/v1")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://soa.ctrip.com/framework/soa/sample/data/v1", IsNullable=true)]
    [DataContract(Namespace="http://soa.ctrip.com/framework/soa/sample/data/v1")]
    [ProtoContract()]
    public partial class RestaurantInfo
    {
        
        private int restaurantIDField;
        
        private string nameField;
        
        private string addressField;
        
        private string cityField;
        
        private string stateField;
        
        private string zipField;
        
        private System.DateTime openFromField;
        
        private System.DateTime openToField;
        
        [DataMember()]
        [ProtoMember(1)]
        public int RestaurantID
        {
            get
            {
                return this.restaurantIDField;
            }
            set
            {
                this.restaurantIDField = value;
            }
        }
        
        [DataMember()]
        [ProtoMember(2)]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        [DataMember()]
        [ProtoMember(3)]
        public string Address
        {
            get
            {
                return this.addressField;
            }
            set
            {
                this.addressField = value;
            }
        }
        
        [DataMember()]
        [ProtoMember(4)]
        public string City
        {
            get
            {
                return this.cityField;
            }
            set
            {
                this.cityField = value;
            }
        }
        
        [DataMember()]
        [ProtoMember(5)]
        public string State
        {
            get
            {
                return this.stateField;
            }
            set
            {
                this.stateField = value;
            }
        }
        
        [DataMember()]
        [ProtoMember(6)]
        public string Zip
        {
            get
            {
                return this.zipField;
            }
            set
            {
                this.zipField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(DataType="time")]
        [DataMember()]
        [ProtoMember(7)]
        public System.DateTime OpenFrom
        {
            get
            {
                return this.openFromField;
            }
            set
            {
                this.openFromField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(DataType="time")]
        [DataMember()]
        [ProtoMember(8)]
        public System.DateTime OpenTo
        {
            get
            {
                return this.openToField;
            }
            set
            {
                this.openToField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soa.ctrip.com/framework/soa/sample/message/v1")]
    [System.Xml.Serialization.XmlRootAttribute("AddRestaurantRequest", Namespace="http://soa.ctrip.com/framework/soa/sample/message/v1", IsNullable=false)]
    [DataContract(Name="AddRestaurantRequest", Namespace="http://soa.ctrip.com/framework/soa/sample/message/v1")]
    [ProtoContract()]
    public partial class AddRestaurantRequestType
    {
        
        private RestaurantInfo restaurantField;
        
        [DataMember()]
        [ProtoMember(1)]
        public RestaurantInfo Restaurant
        {
            get
            {
                return this.restaurantField;
            }
            set
            {
                this.restaurantField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soa.ctrip.com/framework/soa/sample/message/v1")]
    [System.Xml.Serialization.XmlRootAttribute("AddRestaurantResponse", Namespace="http://soa.ctrip.com/framework/soa/sample/message/v1", IsNullable=false)]
    [DataContract(Name="AddRestaurantResponse", Namespace="http://soa.ctrip.com/framework/soa/sample/message/v1")]
    [ProtoContract()]
    public partial class AddRestaurantResponseType : IHasResponseStatus
    {
        
        private ResponseStatusType responseStatusField;
        
        [DataMember()]
        [ProtoMember(1)]
        public ResponseStatusType ResponseStatus
        {
            get
            {
                return this.responseStatusField;
            }
            set
            {
                this.responseStatusField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soa.ctrip.com/framework/soa/sample/message/v1")]
    [System.Xml.Serialization.XmlRootAttribute("RateRestaurantRequest", Namespace="http://soa.ctrip.com/framework/soa/sample/message/v1", IsNullable=false)]
    [DataContract(Name="RateRestaurantRequest", Namespace="http://soa.ctrip.com/framework/soa/sample/message/v1")]
    [ProtoContract()]
    public partial class RateRestaurantRequestType
    {
        
        private int restaurantIDField;
        
        private RatingInfo rateField;
        
        [DataMember()]
        [ProtoMember(1)]
        public int RestaurantID
        {
            get
            {
                return this.restaurantIDField;
            }
            set
            {
                this.restaurantIDField = value;
            }
        }
        
        [DataMember()]
        [ProtoMember(2)]
        public RatingInfo Rate
        {
            get
            {
                return this.rateField;
            }
            set
            {
                this.rateField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soa.ctrip.com/framework/soa/sample/data/v1")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://soa.ctrip.com/framework/soa/sample/data/v1", IsNullable=false)]
    [DataContract(Namespace="http://soa.ctrip.com/framework/soa/sample/data/v1")]
    [ProtoContract()]
    public enum RatingInfo
    {
        
        /// <remarks/>
        [EnumMember()]
        [ProtoEnum()]
        Poor,
        
        /// <remarks/>
        [EnumMember()]
        [ProtoEnum()]
        Good,
        
        /// <remarks/>
        [EnumMember()]
        [ProtoEnum()]
        VeryGood,
        
        /// <remarks/>
        [EnumMember()]
        [ProtoEnum()]
        Excellent,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soa.ctrip.com/framework/soa/sample/message/v1")]
    [System.Xml.Serialization.XmlRootAttribute("RateRestaurantResponse", Namespace="http://soa.ctrip.com/framework/soa/sample/message/v1", IsNullable=false)]
    [DataContract(Name="RateRestaurantResponse", Namespace="http://soa.ctrip.com/framework/soa/sample/message/v1")]
    [ProtoContract()]
    public partial class RateRestaurantResponseType : IHasResponseStatus
    {
        
        private ResponseStatusType responseStatusField;
        
        [DataMember()]
        [ProtoMember(1)]
        public ResponseStatusType ResponseStatus
        {
            get
            {
                return this.responseStatusField;
            }
            set
            {
                this.responseStatusField = value;
            }
        }
    }
    
    /// <summary>
    /// Service client auto-generated by SOA tool, DO NOT CHANGE!
    /// 
    /// 
    /// </summary>
    public class RestaurantServiceClient : ServiceClientBase<RestaurantServiceClient>
    {
        
        public const string CodeGeneratorVersion = "2.0.3.2";
        
        public const string OriginalServiceName = "RestaurantService";
        
        public const string OriginalServiceNamespace = "http://soa.ctrip.com/framework/soa/sample/v1";
        
        private RestaurantServiceClient(string baseUri) : 
                base(baseUri)
        {
        }
        
        private RestaurantServiceClient(string serviceName, string serviceNamespace, string subEnv) : 
                base(serviceName, serviceNamespace, subEnv)
        {
        }
        
        public virtual GetRestaurantsResponseType GetRestaurants(GetRestaurantsRequestType getRestaurantsIn)
        {
            return base.Invoke<GetRestaurantsResponseType>("GetRestaurants", getRestaurantsIn);
        }
        
        public virtual Task<GetRestaurantsResponseType> CreateAsyncTaskOfGetRestaurants(GetRestaurantsRequestType getRestaurantsIn, CancellationToken? cancellationToken = null, TaskCreationOptions? taskCreationOptions = null)
        {
            return base.CreateAsyncTask<GetRestaurantsRequestType, GetRestaurantsResponseType>("GetRestaurants", getRestaurantsIn, cancellationToken, taskCreationOptions);
        }
        
        public virtual Task<GetRestaurantsResponseType> StartIOCPTaskOfGetRestaurants(GetRestaurantsRequestType getRestaurantsIn)
        {
            return base.StartIOCPTask<GetRestaurantsResponseType>("GetRestaurants", getRestaurantsIn);
        }
        
        public virtual AddRestaurantResponseType AddRestaurant(AddRestaurantRequestType addRestaurantIn)
        {
            return base.Invoke<AddRestaurantResponseType>("AddRestaurant", addRestaurantIn);
        }
        
        public virtual Task<AddRestaurantResponseType> CreateAsyncTaskOfAddRestaurant(AddRestaurantRequestType addRestaurantIn, CancellationToken? cancellationToken = null, TaskCreationOptions? taskCreationOptions = null)
        {
            return base.CreateAsyncTask<AddRestaurantRequestType, AddRestaurantResponseType>("AddRestaurant", addRestaurantIn, cancellationToken, taskCreationOptions);
        }
        
        public virtual Task<AddRestaurantResponseType> StartIOCPTaskOfAddRestaurant(AddRestaurantRequestType addRestaurantIn)
        {
            return base.StartIOCPTask<AddRestaurantResponseType>("AddRestaurant", addRestaurantIn);
        }
        
        public virtual RateRestaurantResponseType RateRestaurant(RateRestaurantRequestType rateRestaurantIn)
        {
            return base.Invoke<RateRestaurantResponseType>("RateRestaurant", rateRestaurantIn);
        }
        
        public virtual Task<RateRestaurantResponseType> CreateAsyncTaskOfRateRestaurant(RateRestaurantRequestType rateRestaurantIn, CancellationToken? cancellationToken = null, TaskCreationOptions? taskCreationOptions = null)
        {
            return base.CreateAsyncTask<RateRestaurantRequestType, RateRestaurantResponseType>("RateRestaurant", rateRestaurantIn, cancellationToken, taskCreationOptions);
        }
        
        public virtual Task<RateRestaurantResponseType> StartIOCPTaskOfRateRestaurant(RateRestaurantRequestType rateRestaurantIn)
        {
            return base.StartIOCPTask<RateRestaurantResponseType>("RateRestaurant", rateRestaurantIn);
        }
        
        public virtual CheckHealthResponseType CheckHealth(CheckHealthRequestType checkHealthIn)
        {
            return base.Invoke<CheckHealthResponseType>("CheckHealth", checkHealthIn);
        }
        
        public virtual Task<CheckHealthResponseType> CreateAsyncTaskOfCheckHealth(CheckHealthRequestType checkHealthIn, CancellationToken? cancellationToken = null, TaskCreationOptions? taskCreationOptions = null)
        {
            return base.CreateAsyncTask<CheckHealthRequestType, CheckHealthResponseType>("CheckHealth", checkHealthIn, cancellationToken, taskCreationOptions);
        }
        
        public virtual Task<CheckHealthResponseType> StartIOCPTaskOfCheckHealth(CheckHealthRequestType checkHealthIn)
        {
            return base.StartIOCPTask<CheckHealthResponseType>("CheckHealth", checkHealthIn);
        }
    }
}
